apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykefravaer
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: navikt/sykefravaer:{{version}}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /isAlive
    initialDelay: 0
    periodSeconds: 5
    timeout: 1
    failureThreshold: 3
  readiness:
    path: /isReady
    initialDelay: 0
    periodSeconds: 5
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  vault:
    enabled: true
  ingresses:
    - https://sykefravaer.nais.oera-q.local
    - https://sykefravaer.nais.oera.local
    - https://tjenester-q1.nav.no
    - https://tjenester.nav.no
