version: 2.1
orbs:
  barkendeploy: navikt/barkendeploy@dev:master
jobs:
  linux_build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - setup_remote_docker
      - barkendeploy/init
      - barkendeploy/docker-build
      - barkendeploy/docker-push
  deploy:
    docker:
      - image: "navikt/deployment-cli:v0.1.6"
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Set up environment variables
          command: cat /tmp/workspace/properties.env >> $BASH_ENV
      - run:
          name: Create github deployment for dev-sbs
          command: source $BASH_ENV; deployment-cli deploy create --cluster=dev-sbs --team=teamsykefravr -r=service_account.yaml -r=nais.yaml --version=${DOCKER_TAG} --repository=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
workflows:
  version: 2
  build_and_release:
    jobs:
      - linux_build:
          context: barkendeploy
          filters:
            tags:
              only: naiserator
